const ScreenCatalog = {
	MAIN: 'MAIN',
	HOME: 'HOME',
	KAI_JIANG: 'KAI_JIANG',
	SETTINGS: 'SETTINGS',
	BET_TABLE: 'BET_TABLE',

	ATM: 'ATM',
	ATM_DEPOSIT: 'ATM_DEPOSIT',
	ATM_BANK_SELECTION: 'ATM_BANK_SELECTION',
};

export default ScreenCatalog;
